// ── Occurrence index integration ────────────────────────────────
// The vocabulary dataset stores only ONE example verse per word
// (verseKey/ayahA/ayahT). The occurrence index
// (window.OCCURRENCE_INDEX, generated by scripts/build-occurrence-index.js)
// maps each word's NORMALIZED Arabic form to every verse where the
// token occurs in the Quran. renderExplorerAllOccurrences MERGES both
// sources so "Show all occurrences" lists every indexed occurrence,
// hydrating verse text lazily from the progressive Quran loader
// (only surahs actually needed are loaded). Existing word.occurrences
// entries remain fully supported and take priority.

var _occRenderingToken = 0;
var _occRequestedSurahs = {};

// ── Lazy loading + concurrency control for "Show all occurrences" ──
// Verse text is fetched per surah (window.__quranLoader.loadSurah). We only
// fetch surahs for items as they enter the viewport (with a pre-load buffer)
// instead of loading every surah at once, and we cap how many loadSurah()
// calls are in flight at any time so a fast scroll through a long list can't
// flood the network. Fetched surahs stay cached (loader + _occRequestedSurahs)
// so scrolling back up never re-fetches.
var _occLoadQueue = [];       // surah ids waiting to be fetched (FIFO)
var _occInFlight = 0;         // loadSurah() calls currently running
var _occObserver = null;      // active IntersectionObserver (browser lazy path)
var _occSession = null;       // { token, listEl, w, lazy, pendingCount } hydration target
var OCC_MAX_CONCURRENT_LOADS = 3;   // max simultaneous loadSurah() calls
var OCC_LAZY_PRELOAD_PX = 300;      // start loading this far before an item is visible
var OCC_INITIAL_BATCH = 6;          // distinct surahs preloaded for the first screenful

function _getIndexRefsForWord(w) {
  try {
    if (!w || !w.arabic) return null;
    if (!window.OCCURRENCE_INDEX || typeof window.OCCURRENCE_INDEX_NORM !== 'function') return null;
    var norm = window.OCCURRENCE_INDEX_NORM(w.arabic);
    if (!norm) return null;
    return window.OCCURRENCE_INDEX[norm] || null;
  } catch (e) {
    return null;
  }
}

function _getVerseForRef(ref) {
  try {
    var parts = String(ref).split(':');
    var sid = parseInt(parts[0], 10);
    var vid = parseInt(parts[1], 10);
    if (!sid || !vid) return null;
    var loader = window.__quranLoader;
    if (loader && typeof loader.getVerse === 'function') {
      return loader.getVerse(sid, vid) || null;
    }
    if (window.__QURAN_TEXT && window.__QURAN_TEXT[sid] && window.__QURAN_TEXT[sid].verses) {
      return window.__QURAN_TEXT[sid].verses[vid - 1] || null;
    }
    return null;
  } catch (e) {
    return null;
  }
}

/**
 * Highlight every occurrence of the target word inside a verse's Arabic text.
 *
 * Primary mode: whole-token matching using the SAME normalization the
 * occurrence index was built with (window.OCCURRENCE_INDEX_NORM). The corpus
 * is Uthmani script and the target's dictionary form rarely appears verbatim
 * in it (e.g. مَنْ occurs in the corpus as مِّن / مَّن / مَن — all normalize
 * to "من"), which is why exact-string matching left most indexed occurrences
 * unhighlighted. Token-based matching mirrors exactly how the index decided
 * the verse is an occurrence, so every listed verse highlights consistently.
 *
 * Falls back to the app's normalizeArabic(), then to exact substring
 * matching (legacy behavior, preserving the matched text via $&), when the
 * index normalization is unavailable.
 */
function _highlightOccurrenceText(ayahText, w) {
  if (!ayahText || !w || !w.arabic) return ayahText;
  var normFn = null;
  if (typeof window.OCCURRENCE_INDEX_NORM === 'function') {
    normFn = window.OCCURRENCE_INDEX_NORM;
  } else if (typeof normalizeArabic === 'function') {
    normFn = normalizeArabic;
  }
  if (normFn) {
    var wordNorm = normFn(w.arabic);
    if (wordNorm) {
      var parts = String(ayahText).split(/(\s+)/);
      var out = '';
      for (var i = 0; i < parts.length; i++) {
        var tok = parts[i];
        if (tok && tok.trim() && normFn(tok) === wordNorm) {
          out += '<span class="explorer-ayah-highlight">' + tok + '</span>';
        } else {
          out += tok;
        }
      }
      return out;
    }
  }
  // Last resort: exact substring match (legacy), preserving the matched text.
  var esc = w.arabic.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return String(ayahText).replace(new RegExp(esc, 'g'), '<span class="explorer-ayah-highlight">$&</span>');
}

function _isSurahLoaded(sid) {
  try {
    var loader = window.__quranLoader;
    if (loader && typeof loader.isSurahLoaded === 'function') return loader.isSurahLoaded(sid);
  } catch (e) { /* ignore */ }
  return !!(window.__QURAN_TEXT && window.__QURAN_TEXT[sid]);
}

/**
 * Request a surah's text through the concurrency-capped queue. Dedupes by
 * surah id; never drops a request (failures clear the flag for a later retry).
 */
function _occEnqueueSurah(sid) {
  if (!sid || _occRequestedSurahs[sid] || _isSurahLoaded(sid)) return;
  _occRequestedSurahs[sid] = true;
  _occLoadQueue.push(sid);
  _occPumpLoadQueue();
}

/**
 * Process queued surah loads, keeping at most OCC_MAX_CONCURRENT_LOADS in
 * flight. On success the current session hydrates (per-item in browsers, or
 * one settle re-render in the no-observer fallback). On failure the surah is
 * cleared so a later scroll can retry it.
 */
function _occPumpLoadQueue() {
  while (_occInFlight < OCC_MAX_CONCURRENT_LOADS && _occLoadQueue.length > 0) {
    (function (sid) {
      var session = _occSession;
      _occInFlight++;
      var loader = window.__quranLoader;
      var p = (loader && typeof loader.loadSurah === 'function')
        ? loader.loadSurah(sid)
        : Promise.resolve(false);
      p.then(function () {
        _occInFlight--;
        if (session && session.token === _occRenderingToken) {
          if (session.lazy) {
            _occHydrateSurahItems(session, sid);
          } else if (typeof session.pendingCount === 'number') {
            session.pendingCount--;
            if (session.pendingCount <= 0) {
              // All queued loads settled — one final re-render hydrates the list.
              renderExplorerAllOccurrences(session.listEl, session.w);
            }
          }
        } else if (_occSession && _occSession.token === _occRenderingToken) {
          // A newer render superseded the session that requested this load. The
          // new session's items for this surah were never enqueued (requested-
          // flag dedupe) and would otherwise stick on "Loading…" forever, so
          // hydrate them here instead — per-item in the observer path, or a
          // full re-render of the current list in the fallback path (which
          // picks up every now-loaded surah at once).
          if (_occSession.lazy) {
            _occHydrateSurahItems(_occSession, sid);
          } else if (_occSession.listEl) {
            // Idempotent: each re-render picks up every now-loaded surah at
            // once; still-pending ones stay as placeholders until their own
            // loads complete and trigger the next re-render.
            renderExplorerAllOccurrences(_occSession.listEl, _occSession.w);
          }
        }
        _occPumpLoadQueue();
      }, function () {
        // Non-fatal: refs stay listed. Clear the flag so the item can retry
        // its surah if the user scrolls to it again.
        _occInFlight--;
        delete _occRequestedSurahs[sid];
        if (session && !session.lazy && typeof session.pendingCount === 'number') {
          session.pendingCount--;
          if (session.pendingCount <= 0 && session.token === _occRenderingToken) {
            renderExplorerAllOccurrences(session.listEl, session.w);
          }
        }
        _occPumpLoadQueue();
      });
    })(_occLoadQueue.shift());
  }
}

/**
 * Fill in verse text for every item of a surah in the current session, without
 * re-rendering the list (preserves scroll position and already-loaded items).
 */
function _occHydrateSurahItems(session, sid) {
  if (!session || !session.listEl || typeof session.listEl.querySelectorAll !== 'function') return;
  var items = session.listEl.querySelectorAll('.explorer-occ-item');
  var w = session.w;
  for (var i = 0; i < items.length; i++) {
    var el = items[i];
    if (parseInt(el.getAttribute('data-surah'), 10) !== sid) continue;
    if (el.getAttribute('data-loaded') === '1') continue;
    var ref = el.getAttribute('data-ref');
    var verse = ref ? _getVerseForRef(ref) : null;
    if (!verse) continue;
    var ayahEl = el.querySelector('.explorer-occ-ayah');
    var transEl = el.querySelector('.explorer-occ-trans');
    if (ayahEl) {
      ayahEl.innerHTML = _highlightOccurrenceText(verse.text || '', w);
    }
    if (transEl) transEl.textContent = verse.translation || '';
    el.setAttribute('data-loaded', '1');
    el.setAttribute('data-pending', '0');
  }
}

/**
 * Attach an IntersectionObserver to the occurrence list so verse text only
 * loads for items as they approach the viewport (pre-load buffer included).
 * Returns the observer, or null when IntersectionObserver isn't available.
 */
function _occSetupLazyObserver(listEl, session) {
  if (typeof IntersectionObserver !== 'function' ||
      typeof listEl.querySelectorAll !== 'function') return null;
  if (_occObserver) { _occObserver.disconnect(); _occObserver = null; }
  var observer = new IntersectionObserver(function (entries) {
    for (var e = 0; e < entries.length; e++) {
      if (!entries[e].isIntersecting) continue;
      var el = entries[e].target;
      var sid = parseInt(el.getAttribute('data-surah'), 10);
      if (sid) _occEnqueueSurah(sid);
    }
  }, { root: null, rootMargin: OCC_LAZY_PRELOAD_PX + 'px 0px', threshold: 0 });
  var items = listEl.querySelectorAll('.explorer-occ-item');
  var observed = 0;
  for (var i = 0; i < items.length; i++) {
    if (items[i].getAttribute('data-pending') === '1') {
      observer.observe(items[i]);
      observed++;
    }
  }
  _occObserver = observer;
  return observed > 0 ? observer : null;
}

function renderExplorerAllOccurrences(listEl, w) {
  if (!listEl || !w) {
    if (listEl) listEl.innerHTML = '<div class="ai-empty">No occurrence data available.</div>';
    return;
  }

  var token = ++_occRenderingToken;

  // 1. Merge rich occurrences (word.occurrences) with index refs,
  //    deduplicated by verse reference.
  var byRef = {};
  var list = [];

  function addOcc(o) {
    var ref = o.verseKey || o.ayahR || '';
    if (!ref) return;
    if (byRef[ref]) return;
    byRef[ref] = true;
    list.push(o);
  }

  if (w.occurrences && w.occurrences.length) {
    for (var i = 0; i < w.occurrences.length; i++) addOcc(w.occurrences[i]);
  }

  var indexRefs = _getIndexRefsForWord(w);
  var pendingSurahs = {};
  if (indexRefs && indexRefs.length) {
    for (var r = 0; r < indexRefs.length; r++) {
      var ref = indexRefs[r];
      if (byRef[ref]) continue;
      byRef[ref] = true;
      var verse = _getVerseForRef(ref);
      var parts = String(ref).split(':');
      var sid = parseInt(parts[0], 10);
      if (!verse && sid) pendingSurahs[sid] = true;
      list.push({
        surahId: sid,
        verseKey: ref,
        ayahR: ref,
        ayahA: verse ? verse.text : '',
        ayahT: verse ? verse.translation : '',
        _indexPending: !verse,
      });
    }
  }

  if (list.length === 0) {
    listEl.innerHTML = '<div class="ai-empty">No occurrence data available.</div>';
    return;
  }

  // 2. Render occurrences — free users get a capped preview (5), premium sees all.
  var _hasFullOccurrences = window.__premium && window.__premium.hasFeature &&
    window.__premium.hasFeature(window.__premium.FEATURES.WORD_RELATIONSHIPS);
  var _cap = _hasFullOccurrences ? list.length : Math.min(list.length, 5);
  var html = '<div class="explorer-all-occ-inner">';
  for (var oi = 0; oi < _cap; oi++) {
    var occ = list[oi];
    var surahName = '';
    if (occ.surahId && SURAH_INFO && SURAH_INFO[occ.surahId]) {
      surahName = SURAH_INFO[occ.surahId].name;
    }
    var ref2 = occ.ayahR || occ.verseKey || '';
    // Highlight every occurrence of the target word in the ayah text
    // (token-normalized matching — see _highlightOccurrenceText).
    var ayahText = _highlightOccurrenceText(occ.ayahA || '', w);
    // Ref is rendered instantly; verse text hydrates lazily on scroll for
    // pending (index-only) items. Pending placeholders use the themed muted
    // italic style so they read as loading, not stuck content.
    var pendingItem = !!(occ._indexPending || (!occ.ayahA && !occ.ayahT));
    var trans = occ.ayahT || '';
    var surahAttr = occ.surahId || '';
    html += '<div class="explorer-occ-item" data-surah="' + surahAttr + '" data-ref="' + (ref2 || '') + '" data-pending="' + (pendingItem ? '1' : '0') + '" data-loaded="0">' +
      '<div class="explorer-occ-ref">' + (surahName ? surahName + ' ' : '') + ref2 + '</div>' +
      '<div class="explorer-occ-ayah" lang="ar" dir="rtl">' + ayahText + '</div>' +
      '<div class="explorer-occ-trans">' + (pendingItem ? '<span style="color:var(--text-muted)">Loading…</span>' : trans) + '</div>' +
    '</div>';
  }
  // Free-user upsell below the capped preview (compact line/card, themed).
  if (!_hasFullOccurrences && list.length > 5) {
    html +=
      '<div class="explorer-all-occ-upsell" style="border-top:1px solid var(--gold-dim);margin-top:10px;padding-top:10px;text-align:center">' +
        '<div style="font-family:var(--serif);font-size:13px;color:var(--gold-light);margin-bottom:6px">See all ' + list.length + ' occurrences — Premium</div>' +
        '<button class="btn btn-sm" type="button" onclick="if(window.__premium)window.__premium.requestUpgrade(\'word-relationships\')">⭐ Upgrade to Premium</button>' +
      '</div>';
  }
  html += '</div>';
  listEl.innerHTML = html;

  // 3. Hydrate verse text lazily. In browsers, an IntersectionObserver only
  //    requests surahs for items as they enter (or approach) the viewport, so
  //    a word with hundreds of refs never fires a wall of requests at once.
  //    A small initial batch preloads the first screenful so there is no
  //    visible "Loading…" flash at the top. Without an observer (tests / very
  //    old browsers) every pending surah is requested through the same capped
  //    queue, with one settle re-render — identical to the previous eager
  //    behavior but concurrency-limited.
  var session = { token: token, listEl: listEl, w: w, lazy: false };
  _occSession = session;
  var observer = _occSetupLazyObserver(listEl, session);
  session.lazy = !!observer;

  if (observer) {
    // Preload the first screenful of pending surahs through the capped queue.
    var preloaded = {};
    var items = listEl.querySelectorAll('.explorer-occ-item');
    var batch = 0;
    for (var pb = 0; pb < items.length && batch < OCC_INITIAL_BATCH; pb++) {
      if (items[pb].getAttribute('data-pending') !== '1') continue;
      var pSid = parseInt(items[pb].getAttribute('data-surah'), 10);
      if (pSid && !preloaded[pSid]) { preloaded[pSid] = true; _occEnqueueSurah(pSid); batch++; }
    }
  } else {
    // No observer: request every pending surah now (capped at 3 in flight),
    // and re-render once they have all settled.
    session.pendingCount = 0;
    for (var s in pendingSurahs) {
      if (!pendingSurahs.hasOwnProperty(s)) continue;
      var sidNum = parseInt(s, 10);
      if (!_occRequestedSurahs[String(sidNum)] && !_isSurahLoaded(sidNum)) {
        session.pendingCount++;
        _occEnqueueSurah(sidNum);
      }
    }
  }
}

// Export explorer for cross-module access


window.__openExplorer = openExplorer;
window.__explorerWord = function() { return _explorerWord; };

// ═══════════════════════════════════════════════════════════════

// ═══════════════════════════════════════════════════════════════
// COMPREHENSION ANIMATIONS — Smooth number counting, ring fill, milestone celebration
// ═══════════════════════════════════════════════════════════════

/**
 * Animate a number element counting from 0 to target.
 * @param {Element} el - The DOM element to update
 * @param {number} target - The target value (0-100)
 * @param {number} duration - Animation duration in ms (default 800)
 */
function animateComprehensionNumber(el, target, duration) {
  if (!el) return;
  duration = duration || 800;
  var startTime = null;
  var startVal = 0;
  
  function step(timestamp) {
    if (!startTime) startTime = timestamp;
    var progress = Math.min(1, (timestamp - startTime) / duration);
    // Ease out cubic
    var eased = 1 - Math.pow(1 - progress, 3);
    var current = Math.round(eased * target);
    el.textContent = current + '%';
    if (progress < 1) {
      requestAnimationFrame(step);
    } else {
      el.textContent = target + '%';
      el.classList.add('animate-count');
    }
  }
  
  requestAnimationFrame(step);
}

/**
 * Animate the SVG comprehension ring from 0 to target percent.
 * @param {Element} ringEl - The SVG path element for the ring fill
 * @param {number} targetPercent - The final percentage (0-100)
 * @param {number} duration - Animation duration in ms (default 800)
 */
function animateComprehensionRing(ringEl, targetPercent, duration) {
  if (!ringEl) return;
  duration = duration || 800;
  var startTime = null;
  targetPercent = Math.min(100, Math.max(0, targetPercent));
  
  // Save original transition and disable it during animation to avoid conflict
  var origTransition = ringEl.style.transition;
  ringEl.style.transition = 'none';
  
  // Start at 0
  ringEl.setAttribute('stroke-dasharray', '0, 100');
  
  function step(timestamp) {
    if (!startTime) startTime = timestamp;
    var progress = Math.min(1, (timestamp - startTime) / duration);
    // Ease out cubic with slight overshoot
    var eased = 1 - Math.pow(1 - progress, 3);
    var current = Math.round(eased * targetPercent);
    ringEl.setAttribute('stroke-dasharray', current + ', 100');
    if (progress < 1) {
      requestAnimationFrame(step);
    } else {
      // Restore original transition
      ringEl.style.transition = origTransition || '';
    }
  }
  
  // Force layout to ensure 'none' transition is applied before first frame
  void ringEl.getBoundingClientRect();
  requestAnimationFrame(step);
}

/**
 * Trigger a milestone celebration effect on the comprehension card.
 * @param {Element} cardEl - The dashboard comprehension card element
 */
function triggerMilestoneCelebration(cardEl) {
  if (!cardEl) return;
  
  // Add celebration class
  cardEl.classList.add('milestone-celebration', 'milestone-confetti');
  
  // Pulse the ring
  var ringWrap = cardEl.querySelector('.db-ring-wrap');
  if (ringWrap) ringWrap.classList.add('animate-ring-pulse');
  
  // Remove animation classes after they complete
  setTimeout(function() {
    cardEl.classList.remove('milestone-celebration', 'milestone-confetti');
    if (ringWrap) ringWrap.classList.remove('animate-ring-pulse');
  }, 2000);
}

/**
 * Animate delta rows with staggered entrance
 * @param {Element} container - The parent element containing delta rows
 */
function animateDeltaRows(container) {
  if (!container) return;
  var rows = container.querySelectorAll('.db-delta-row, .db-milestone-row, .db-insight-message, .db-next-milestone');
  for (var i = 0; i < rows.length; i++) {
    rows[i].classList.add('animate-delta');
    // Use JS-applied delays instead of CSS nth-child (which counts all siblings)
    rows[i].style.animationDelay = (0.4 + i * 0.1) + 's';
  }
}

/**
 * Full comprehension animation sequence for the dashboard card.
 * @param {Element} cardEl - The dashboard comprehension card
 * @param {number} comprehensionPct - The comprehension percentage to animate to
 * @param {boolean} isNewMilestone - Whether a new milestone was just reached
 */
function animateDashboardComprehension(cardEl, comprehensionPct, isNewMilestone) {
  if (!cardEl) return;
  
  var ringEl = cardEl.querySelector('.db-ring-fill');
  var ringText = cardEl.querySelector('.db-ring-text');
  var ringWrap = cardEl.querySelector('.db-ring-wrap');
  
  // Animate ring fill from 0 to target
  if (ringEl) {
    animateComprehensionRing(ringEl, comprehensionPct);
  }
  
  // Animate ring text number counting up
  if (ringText) {
    animateComprehensionNumber(ringText, comprehensionPct);
  }
  
  // Ring glow effect
  if (ringWrap) {
    ringWrap.classList.add('animate-ring-glow');
    setTimeout(function() {
      ringWrap.classList.remove('animate-ring-glow');
    }, 1500);
  }
  
  // Staggered delta row entrance
  animateDeltaRows(cardEl);
  
  // Milestone celebration
  if (isNewMilestone) {
    triggerMilestoneCelebration(cardEl);
  }
}

// LEARNING PATH DASHBOARD — Multi-Path Progress & Selection
// ═══════════════════════════════════════════════════════════════

/**
 * Render the Learning Path Dashboard.
 * Called by switchView('dashboard').
 */